<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddMerchantItem</name>
   <tag></tag>
   <elementGuidId>93f50fe4-726b-4bfa-b2c7-aebbd537af6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAddMerchantItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddMerchantItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acc7f8d9-f6bd-4965-a130-2c8fcfd0060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAddMerchantItem</value>
      <webElementGuid>7e9a9671-7433-4824-8803-9c8c2613de59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddMerchantItem</value>
      <webElementGuid>12b20142-2b38-4ccc-9b92-ee9cc8feadb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>90baeb1c-4917-4beb-b3c4-9c656e0bb470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b584718-8384-44ee-aee6-fcbfa92f7be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return AddMerchantItem();</value>
      <webElementGuid>f79abac5-9486-455f-ba00-394e94f3aadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>cb9b45d9-1485-4a44-afa5-7c3a076bb8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddMerchantItem&quot;)</value>
      <webElementGuid>33224271-9ed5-4064-bf33-42a6093aa219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAddMerchantItem']</value>
      <webElementGuid>0ed308a9-5dcf-458a-85cd-d43cff56ecab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmmerchantitem']/div[26]/input</value>
      <webElementGuid>7251971f-3fe2-4ebd-a5c9-8589452a9455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/input</value>
      <webElementGuid>70de12dc-2a35-4297-b437-05ec8f874a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnAddMerchantItem' and @id = 'btnAddMerchantItem' and @type = 'button']</value>
      <webElementGuid>ea6bf733-dace-4c3e-8890-1b64b6b4507e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
