<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Item</name>
   <tag></tag>
   <elementGuidId>7d0903ab-9f6a-4c37-b4ef-66e6e19ee5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnpopupaddmerchantItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnpopupaddmerchantItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7665c3e-58d7-4a46-8144-0e261d4d477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnpopupaddmerchantItem</value>
      <webElementGuid>4da2ab1f-a49e-4fd2-876d-7e0c6ebcefc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-light mainaddbuttons</value>
      <webElementGuid>fd267f48-f83b-413b-89f1-07f79dba227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f655c20b-fb39-47c3-9e6d-6a913afebc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return PopupAddMerchantItem();</value>
      <webElementGuid>ed6a5364-9bbf-4d39-b323-89f53b6d25a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>1fd004ab-5e9f-40b1-9c28-5a2eb34dea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnpopupaddmerchantItem&quot;)</value>
      <webElementGuid>4ef6eecd-df4b-4f95-be78-62a60f7444c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnpopupaddmerchantItem']</value>
      <webElementGuid>66e5e405-d723-49a8-ba95-60d1a2133496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDetails']/div[2]/div/button</value>
      <webElementGuid>f0814c65-ad07-4d26-8c35-827bdce95b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export to'])[1]/following::button[1]</value>
      <webElementGuid>c5d5271f-ea15-4d22-b595-108ee977c0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[3]/following::button[1]</value>
      <webElementGuid>81238def-cc0b-413d-8cc2-c671b30d02d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/preceding::button[1]</value>
      <webElementGuid>01e883ee-c819-44e5-9bbe-bfc0897eb6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Name'])[1]/preceding::button[1]</value>
      <webElementGuid>249168c5-5fe5-42b6-9d0b-62d230eb9d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Item']/parent::*</value>
      <webElementGuid>3e21f5eb-9ca0-4f2c-ac9f-20a39b3db2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>b6bf71f9-79a6-4891-a8b5-ee532ee1b1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnpopupaddmerchantItem' and (text() = 'Add Item' or . = 'Add Item')]</value>
      <webElementGuid>21fe0123-4330-4580-9fb8-372ff6ff4468</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
