<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_itemName</name>
   <tag></tag>
   <elementGuidId>a0135b29-39aa-455b-b042-5bb622a4501c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtItemName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtItemName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a17a4529-776b-4cfd-97b1-65251b556a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aff9a27e-c229-44bb-bf9f-a5cbb1a33112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtItemName</value>
      <webElementGuid>301d112d-2099-4e2d-95a4-d1bd44b49e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>052cd5c5-c018-430e-9ffa-286bdc9fa951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MerchantItem.ItemName</value>
      <webElementGuid>196e0187-3fe6-4a58-b997-97594973e7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkmerchantitemname();</value>
      <webElementGuid>7431ef1d-965b-4e56-93b0-1a0a1bb9abae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c7c143b-e5e7-4ef2-ba66-687354acdeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtItemName&quot;)</value>
      <webElementGuid>b70ea621-1151-4781-8143-2376c22e5969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtItemName']</value>
      <webElementGuid>42950152-cb9c-4413-95da-6d4eea6475c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmmerchantitem']/div[2]/div/input</value>
      <webElementGuid>580f4a85-53d0-461c-bd3d-396dbb617f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5dc51620-97ff-4270-91c6-45d80931167e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtItemName' and @name = 'MerchantItem.ItemName' and @type = 'text']</value>
      <webElementGuid>f952dbda-0aae-4b11-9c83-4b3042771c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
