<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_itemNameAr</name>
   <tag></tag>
   <elementGuidId>8822ae98-f545-48bc-bb9a-3f0b1847f720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtItemNameAr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtItemNameAr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>789d101b-849c-4b84-883e-b6efbc58a31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fad5c9e8-4eb3-44f0-a0f0-583c2ad69045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtItemNameAr</value>
      <webElementGuid>c300edca-9f82-4036-8917-326b1f98d455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>ff4a4c04-0a52-4fba-9bb3-8c3f71d54177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MerchantItem.ItemNameAr</value>
      <webElementGuid>9953a466-a622-4f60-86bd-24bf6d866be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkmerchantitemnamearabic();</value>
      <webElementGuid>3ddf8fc2-cff9-44d5-9f3b-b9eef14612e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>622cb6a2-8485-4916-9634-e6f8ffd7cad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtItemNameAr&quot;)</value>
      <webElementGuid>6e48693b-6dbf-4f0d-9f37-0cf5db07bc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtItemNameAr']</value>
      <webElementGuid>cba9051a-51b7-4512-9170-d0ec6de92aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmmerchantitem']/div[3]/div/input</value>
      <webElementGuid>0b2a567b-da10-450a-b130-092a2b7ffaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c152106c-4cc4-449f-aaea-681823ccff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtItemNameAr' and @name = 'MerchantItem.ItemNameAr' and @type = 'text']</value>
      <webElementGuid>9c189dfc-216a-4257-8ef8-c436dca53512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
